**LABELS**
ds idealpointfp*
foreach v of varlist `r(varlist)' {
    local newname = subinstr("`v'", "idealpointfp", "", 1)
    rename `v' `newname'
}

label var AFG "Afghanistan"
label var AGO "Angola"
label var ALB "Albania"
label var AND "Andorra"
label var ARE "United Arab Emirates"
label var ARG "Argentina"
label var ARM "Armenia"
label var ATG "Antigua and Barbuda"
label var AUS "Australia"
label var AUT "Austria"
label var AZE "Azerbaijan"
label var BDI "Burundi"
label var BEL "Belgium"
label var BEN "Benin"
label var BFA "Burkina Faso"
label var BGD "Bangladesh"
label var BGR "Bulgaria"
label var BHR "Bahrain"
label var BHS "Bahamas"
label var BIH "Bosnia and Herzegovina"
label var BLR "Belarus"
label var BLZ "Belize"
label var BOL "Bolivia"
label var BRA "Brazil"
label var BRB "Barbados"
label var BRN "Brunei"
label var BTN "Bhutan"
label var BWA "Botswana"
label var CAF "Central African Republic"
label var CAN "Canada"
label var CHE "Switzerland"
label var CHL "Chile"
label var CHN "China"
label var CIV "Côte d'Ivoire"
label var CMR "Cameroon"
label var COD "Democratic Republic of the Congo"
label var COG "Republic of the Congo"
label var COL "Colombia"
label var COM "Comoros"
label var CPV "Cape Verde"
label var CRI "Costa Rica"
label var CUB "Cuba"
label var CYP "Cyprus"
label var CZE "Czech Republic"
label var DEU "Germany"
label var DJI "Djibouti"
label var DMA "Dominica"
label var DNK "Denmark"
label var DOM "Dominican Republic"
label var DZA "Algeria"
label var ECU "Ecuador"
label var EGY "Egypt"
label var ERI "Eritrea"
label var ESP "Spain"
label var EST "Estonia"
label var ETH "Ethiopia"
label var FIN "Finland"
label var FJI "Fiji"
label var FRA "France"
label var FSM "Micronesia"
label var GAB "Gabon"
label var GBR "United Kingdom"
label var GEO "Georgia"
label var GHA "Ghana"
label var GIN "Guinea"
label var GMB "Gambia"
label var GNB "Guinea-Bissau"
label var GNQ "Equatorial Guinea"
label var GRC "Greece"
label var GRD "Grenada"
label var GTM "Guatemala"
label var GUY "Guyana"
label var HND "Honduras"
label var HRV "Croatia"
label var HTI "Haiti"
label var HUN "Hungary"
label var IDN "Indonesia"
label var IND "India"
label var IRL "Ireland"
label var IRN "Iran"
label var IRQ "Iraq"
label var ISL "Iceland"
label var ISR "Israel"
label var ITA "Italy"
label var JAM "Jamaica"
label var JOR "Jordan"
label var JPN "Japan"
label var KAZ "Kazakhstan"
label var KEN "Kenya"
label var KGZ "Kyrgyzstan"
label var KHM "Cambodia"
label var KIR "Kiribati"
label var KNA "Saint Kitts and Nevis"
label var KOR "South Korea"
label var KWT "Kuwait"
label var LAO "Laos"
label var LBN "Lebanon"
label var LBR "Liberia"
label var LBY "Libya"
label var LCA "Saint Lucia"
label var LIE "Liechtenstein"
label var LKA "Sri Lanka"
label var LSO "Lesotho"
label var LTU "Lithuania"
label var LUX "Luxembourg"
label var LVA "Latvia"
label var MAR "Morocco"
label var MCO "Monaco"
label var MDA "Moldova"
label var MDG "Madagascar"
label var MDV "Maldives"
label var MEX "Mexico"
label var MHL "Marshall Islands"
label var MKD "North Macedonia"
label var MLI "Mali"
label var MLT "Malta"
label var MMR "Myanmar"
label var MNE "Montenegro"
label var MNG "Mongolia"
label var MOZ "Mozambique"
label var MRT "Mauritania"
label var MUS "Mauritius"
label var MWI "Malawi"
label var MYS "Malaysia"
label var NAM "Namibia"
label var NER "Niger"
label var NGA "Nigeria"
label var NIC "Nicaragua"
label var NLD "Netherlands"
label var NOR "Norway"
label var NPL "Nepal"
label var NRU "Nauru"
label var NZL "New Zealand"
label var OMN "Oman"
label var PAK "Pakistan"
label var PAN "Panama"
label var PER "Peru"
label var PHL "Philippines"
label var PLW "Palau"
label var PNG "Papua New Guinea"
label var POL "Poland"
label var PRK "North Korea"
label var PRT "Portugal"
label var PRY "Paraguay"
label var QAT "Qatar"
label var ROU "Romania"
label var RUS "Russia"
label var RWA "Rwanda"
label var SAU "Saudi Arabia"
label var SDN "Sudan"
label var SEN "Senegal"
label var SGP "Singapore"
label var SLB "Solomon Islands"
label var SLE "Sierra Leone"
label var SLV "El Salvador"
label var SMR "San Marino"
label var SOM "Somalia"
label var SSD "South Sudan"
label var STP "São Tomé and Príncipe"
label var SUR "Suriname"
label var SVK "Slovakia"
label var SVN "Slovenia"
label var SWE "Sweden"
label var SWZ "Eswatini"
label var SYC "Seychelles"
label var SYR "Syria"
label var TCD "Chad"
label var TGO "Togo"
label var THA "Thailand"
label var TJK "Tajikistan"
label var TKM "Turkmenistan"
label var TLS "Timor-Leste"
label var TON "Tonga"
label var TTO "Trinidad and Tobago"
label var TUN "Tunisia"
label var TUR "Turkey"
label var TUV "Tuvalu"
label var TZA "Tanzania"
label var UGA "Uganda"
label var UKR "Ukraine"
label var URY "Uruguay"
label var USA "United States"
label var UZB "Uzbekistan"
label var VCT "Saint Vincent and the Grenadines"
label var VEN "Venezuela"
label var VNM "Vietnam"
label var VUT "Vanuatu"
label var WSM "Samoa"
label var YEM "Yemen"
label var YUG "Yugoslavia (former)"
label var ZAF "South Africa"
label var ZMB "Zambia"
label var ZWE "Zimbabwe"
